name: Deploy (after successful build and test)

on:
  push:
    branches:
    - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  depoly-windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
      with:
        repository: medyan-dev/medyan
        token: ${{ secrets.MEDYAN_BOT_PAT_REPO }}
        path: medyan
    - name: prepare dependencies
      run: |
        .\medyan\conf.ps1
    - name: build with MSBuild
      working-directory: medyan
      run: |
        cd build
        & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" .\MEDYAN.sln /property:Configuration=Release /property:Platform=x64
    - name: run tests
      working-directory: medyan
      run: |
        ls -lha .\build\Release
        .\build\Release\medyan.exe test

  deploy-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: medyan-dev/medyan
        token: ${{ secrets.MEDYAN_BOT_PAT_REPO }}
        path: medyan
    - name: prepare dependencies
      working-directory: medyan
      run: |
        brew install pkg-config
        sed -i '' -e 's/-mtune=native -march=native/-mavx/g' CMakeLists.txt
        ./conf.sh
    - name: build with make
      working-directory: medyan
      run: |
        cd build
        make VERBOSE=1
    - name: run tests
      working-directory: medyan
      run: |
        ./build/medyan test
