name: Deploy (after successful build and test)

on:
  push:
    branches:
    - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  nightly:
    name: nightly deploy
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: medyan-dev/medyan
        token: ${{ secrets.MEDYAN_BOT_PAT_REPO }}
        path: medyan
        fetch-depth: 0

    - name: prepare dependencies (ubuntu)
      if: matrix.os == 'ubuntu-latest'
      working-directory: medyan
      run: |
        # required by glfw3 library
        sudo apt-get update && sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev
        # Use avx2 (default avx512 causes trouble in UMEsimd)
        sed -i 's/-mtune=native -march=native/-mavx2 -mno-avx512f/g' CMakeLists.txt
        # add --no-as-needed to correctly link pthread
        sed -i -e '/    target_link_libraries(medyan PRIVATE Threads::Threads)/a\' -e '    target_link_options(medyan BEFORE PRIVATE "-Wl,--no-as-needed")' CMakeLists.txt
        ./conf.sh
    - name: prepare dependencies (windows)
      working-directory: medyan
      if: matrix.os == 'windows-latest'
      run: |
        .\conf.ps1
    - name: prepare dependencies (macos)
      if: matrix.os == 'macos-latest'
      working-directory: medyan
      run: |
        brew install pkg-config
        sed -i '' -e 's/-mtune=native -march=native/-mavx/g' CMakeLists.txt
        ./conf.sh

    - name: build (windows with MSBuild)
      if: matrix.os == 'windows-latest'
      working-directory: medyan
      run: |
        cd build
        & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" .\MEDYAN.sln /property:Configuration=Release /property:Platform=x64
        ls Release
    - name: build (macos/ubuntu with make)
      if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
      working-directory: medyan
      run: |
        cd build
        make VERBOSE=1
        ls build

    - name: run tests (windows)
      if: matrix.os == 'windows-latest'
      working-directory: medyan
      run: |
        .\build\Release\medyan.exe test
    - name: run tests (macos/ubuntu)
      if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
      working-directory: medyan
      run: |
        ./build/medyan test

    - name: bundle files (windows)
      if: matrix.os == 'windows-latest'
      working-directory: medyan
      run: |
        $compress = @{
          Path = ".\build\Release\medyan.exe"
          CompressionLevel = "Fastest"
          DestinationPath = ".\build\Release\medyan.zip"
        }
        Compress-Archive @compress
    - name: bundle files (macos/ubuntu)
      if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
      working-directory: medyan
      run: |
        cd build
        zip medyan.zip medyan

    - name: deploy release (ubuntu)
      if: matrix.os == 'ubuntu-latest'
      uses: WebFreak001/deploy-nightly@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/medyan-dev/medyan-public/releases/65013247/assets{?name,label}
        release_id: 65013247
        asset_path: ./medyan/build/medyan.zip
        asset_name: medyan-x86_64-linux.zip
        asset_content_type: application/zip
        max_releases: 1
    - name: deploy release (windows)
      if: matrix.os == 'windows-latest'
      uses: WebFreak001/deploy-nightly@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/medyan-dev/medyan-public/releases/65013247/assets{?name,label}
        release_id: 65013247
        asset_path: .\medyan\build\Release\medyan.zip
        asset_name: medyan-x86_64-win.zip
        asset_content_type: application/zip
        max_releases: 1
    - name: deploy release (macos)
      if: matrix.os == 'macos-latest'
      uses: WebFreak001/deploy-nightly@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/medyan-dev/medyan-public/releases/65013247/assets{?name,label}
        release_id: 65013247
        asset_path: ./medyan/build/medyan.zip
        asset_name: medyan-x86_64-macos.zip
        asset_content_type: application/zip
        max_releases: 1
